mgongora07/HENRYBUSTER-main

- api/src/controllers/fillMovie.js
> Peliculas Agregadas al inventario

- api/src/controllers/insertFormat.js
- api/src/controllers/insertGenre.js
- api/src/controllers/insertLanguage.js
- api/src/routes/index.js
> Insert format

- api/src/controllers/insertGenre.js
- api/src/routes/index.js
> InsertGenre controller and route

- api/src/controllers/insertGenre.js
- api/src/controllers/insertLanguage.js
- api/src/routes/index.js
> Insert language

- api/src/controllers/insertFormat.js
- api/src/controllers/insertGenre.js
- api/src/controllers/insertLanguage.js
- api/src/controllers/insertMovie.js
- api/src/controllers/insertUser.js
- api/src/routes/index.js
> Insert movie

- api/src/controllers/insertFormat.js
- api/src/controllers/insertGenre.js
- api/src/controllers/insertLanguage.js
- api/src/controllers/insertUser.js
- api/src/routes/index.js
> Insert user

- api/src/controllers/fillMovie.js
27 movies added to fillMovie.js controller
> 27 more movies added

- api/src/controllers/UpdateMovie.js
- api/src/controllers/getMovieById.js
- api/src/controllers/getRatingsByMovieId.js
- api/src/controllers/getUserById.js
- api/src/controllers/getUsers.js
- api/src/controllers/insertFormat.js
- api/src/controllers/insertGenre.js
- api/src/controllers/insertLanguage.js
- api/src/controllers/insertMovie.js
- api/src/controllers/insertUser.js
- api/src/controllers/updateUser.js
- api/src/routes/index.js
get all the coments and ratings by MovieId
/rating/:id
> Get ratings by movie

- api/src/controllers/fillMovie.js
- api/src/controllers/fillRating.js
- api/src/controllers/fillUser.js
- api/src/controllers/insertUser.js
- api/src/models/User.js
cambios para adaptacion modelo de miguel, con el llenado de comentarios pedido de los del front, el modelo cambiado segun los rquerimientos de miguel, y otra funciones cambiadas para adaptarse al modelo como el fillUser
> Cambios modelo user miguel

- client/henrybuster/src/App.jsx
- client/henrybuster/src/components/Carrito/Cart.css
- client/henrybuster/src/components/Carrito/Cart.jsx
- client/henrybuster/src/components/Carrito/Context.jsx
- client/henrybuster/src/components/Carrito/ItemCart.jsx
- client/henrybuster/src/components/Detail/Detail.jsx
- client/henrybuster/src/components/Nav/Nav.jsx
- client/henrybuster/src/components/Styles/Carrito.module.css
> Carrito desde Details

- api/src/controllers/fillMovie.js
> 100 peliculas

- client/henrybuster/src/components/Detail/EachReview.jsx
- client/henrybuster/src/components/Detail/Reviews.jsx
- client/henrybuster/src/redux/action-type.js
- client/henrybuster/src/redux/actions.js
- client/henrybuster/src/redux/reducer.js
Reviews paginados, 
Ademas, el reducer tenia duplicado un import que corregi mal, pero ahora ya esta bien en esta version
> reviews paginados

- api/src/controllers/getMoviesForAdmin.js
- api/src/routes/index.js
se creose agrego la logica en en econtrolar de pedir peliculas que filtre los que no tienen stock, y se agrego una ruta que para el admin muestres todas las peliculas incluso las que no estan en stock
> GetMoviesByAdminAndfixGetMovies

- api/src/controllers/fillMovie.js
se agrego una funcion random para dar valores random iniciales a los rating de cada pelicula para que tengan un rating inicial y los del front puedan seguir haciendo pruebas, pedido por franco
> AddRatingMovies

- api/src/controllers/searchMovieByName.js
- api/src/routes/index.js
ejemeplo de como usar la ruta   de buscar por nombre    http://localhost:3001/movies/search?name=ca
> searchMovieByName

- client/henrybuster/package-lock.json
- client/henrybuster/package.json
- client/henrybuster/src/App.jsx
- client/henrybuster/src/components/Home/Home.jsx
- client/henrybuster/src/components/SearchBar/SearchBar.jsx
- client/henrybuster/src/components/SearchBar/SearchResult.jsx
- client/henrybuster/src/components/Styles/SearchResult.module.css
- client/henrybuster/src/redux/reducer.js
SarchBar Funcionando, se agrego funcionalidad en el estado de redux
> SearchBar Funcionando

- client/henrybuster/package-lock.json
- client/henrybuster/package.json
- client/henrybuster/src/App.jsx
- client/henrybuster/src/components/Admin/Admin.jsx
- client/henrybuster/src/components/Admin/HomeAdmin.css
- client/henrybuster/src/components/Admin/HomeAdmin.jsx
- client/henrybuster/src/components/Admin/MoviesAdmin/MoviesAdmin.jsx
- client/henrybuster/src/components/Admin/MoviesAdmin/SearchBarAdmin.jsx
- client/henrybuster/src/components/Admin/Sidebar.css
- client/henrybuster/src/components/Admin/Sidebar.jsx
- client/henrybuster/src/components/CreateGenre/CreateGenre.jsx
- client/henrybuster/src/components/CreateMovie/CreateMovie.jsx
- client/henrybuster/src/components/UpdateMovie/UpdateMovie.jsx
- package-lock.json
- package.json
Necesito una mano con el bootstrap
> Componentes integrados al panel de admin

- api/src/controllers/searchMovieByName.js
- api/src/controllers/searchMovieForGuest.js
- api/src/routes/index.js
> Fix2 search

- api/src/controllers/searchMovieByName.js
- api/src/controllers/searchMovieForGuest.js
- api/src/routes/index.js
- client/henrybuster/src/redux/actions.js
> Search fix front

- api/src/controllers/deleteMovie.js
- api/src/controllers/getMovieById.js
- api/src/controllers/getMovies.js
- api/src/controllers/updateGenre.js
- api/src/models/Movie.js
- api/src/routes/index.js
agregado el status al modelo pelicula, cambio de logica de los get movies, agreegado el delete Movies cambiando el status de pelicula, y cambiado de la respuesta del; bacy en el get movie id en el date
> Status movie and delete

- api/src/controllers/getMovies.js
- api/src/controllers/getMoviesForAdmin.js
el admin ya no puede ver lo que elimino
> getMovieFix

- client/henrybuster/src/components/Detail/Detail.jsx
- client/henrybuster/src/components/Detail/EachReview.jsx
- client/henrybuster/src/components/Detail/Reviews.jsx
- client/henrybuster/src/components/Styles/Detail.module.css
- client/henrybuster/src/components/Styles/EachReview.module.css
- client/henrybuster/src/components/Styles/Reviews.module.css
> CSS de reviews

- client/henrybuster/src/App.jsx
- client/henrybuster/src/components/Home/Home.jsx
- client/henrybuster/src/components/Home/agregadasRecientemente/NewMovie.module.css
- client/henrybuster/src/components/Home/cards/Cards.jsx
- client/henrybuster/src/components/Home/cards/Cards.module.css
- client/henrybuster/src/components/Home/carrusel/carrusel.module.css
- client/henrybuster/src/components/Home/paginado/Paginado.module.css
- client/henrybuster/src/components/Styles/Home.module.css
Se modifico el estilo de las card, y la vista del Home, paginador y cambio de idioma en home
> update card 2.0 and modify home

- api/src/controllers/deleteGenre.js
- api/src/models/Genre.js
- client/henrybuster/src/components/CreateMovie/CreateMovie.jsx
- client/henrybuster/src/components/UpdateMovie/UpdateMovie.jsx
> fixupdatemov

- api/src/controllers/fillMovie.js
> moreMovies

- api/package-lock.json
- api/package.json
- api/src/controllers/InsertPurchase.js
- api/src/controllers/insertGuestPurchase.js
- api/src/db.js
- api/src/models/Address.js
- api/src/models/User.js
- api/src/routes/index.js
compras para los usuario y los invitados
> InsertarCompras

- api/src/controllers/InsertPurchase.js
- api/src/controllers/getPurchases.js
- api/src/controllers/insertGuestPurchase.js
- api/src/db.js
- api/src/models/Purchase.js
- api/src/models/PurchaseMovie.js
- api/src/models/User.js
- api/src/routes/index.js
ruta para ver todas la compras, tablas de compras arreglado con lko discutido en clase
> comprasArregladas

- api/src/controllers/updatePuchaseById.js
agregado que cuando se cancele la orde devuelva el valor del inventario
> cancelacionPelicula

- client/henrybuster/src/components/Carrito/CheckoutForm.jsx
- client/henrybuster/src/components/Carrito/Payment.jsx
- client/henrybuster/src/components/Users/OrderAdress.jsx
- client/henrybuster/src/redux/action-type.js
- client/henrybuster/src/redux/actions.js
- client/henrybuster/src/redux/reducer.js
carritop arreglado funcionando aunque le falta detallitos
> fixcarrito

- client/henrybuster/src/components/Nav/Nav.jsx
- client/henrybuster/src/components/Styles/Nav.module.css
arreglo del logo yt centrado del usuario
> arreglosNavbar

- api/src/controllers/getPurchaseByUserId.js
- api/src/routes/index.js
ruta para pedir usuario por id
> compraByUserId

- client/henrybuster/src/components/Carrito/CheckoutForm.jsx
- client/henrybuster/src/components/Carrito/Payment.jsx
Notificaciones al realizar la compra
> Develop log notifica

- client/henrybuster/package-lock.json
- client/henrybuster/src/App.jsx
- package-lock.json
- package.json
> Bot y rutas protegidas
